name: cicd for python

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps: 
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: docker run
        run: docker run -v ./app.py:/root/app.py busybox cat /root/app.py 
